stages:
  - build
  - test
  - deploy

test:
  image: node:14
  stage: test
  script:
    - npm install
    - npm test

build:
  image: node:14
  stage: build
  script:
    - npm install
    - npm build
  artifacts:
    paths:
      - build/

deploy:
  image: node:14
  stage: deploy
  script:
    - npm install

trigger_pipeline:
  stage: deploy
  script:
    - 'curl --fail --request POST --form token=7ae43062ddd46e803654ae33cd4885 --form ref=master https://gitlab.com/api/v4/projects/32878876/trigger/pipeline"'
  rules:
    - if: $CI_COMMIT_TAG

netlify:
  stage: deploy
  image: node:14
  script:
      - npm install -g netlify-cli
      - netlify deploy --dir=build --prod
