stages:
  - build
  - test
  - install

install:
  image: node:14
  stages: install
  script:
    - npm install

build:
  image: node:14
  stage: build
  script:
    - npm build

test:
  image: node:14
  stage: test
  script:
    - npm test
