stages:
  - build
  - test
  - deploy

deploy:
  image: node:14
  stages: deploy
  script:
    - npm install

build:
  image: node:14
  stage: build
  script:
    - npm build

test:
  image: node:14
  stage: test
  script:
    - npm test
